[theme]
primaryColor = "#B583F2"              # Light purple (icons, buttons)
backgroundColor = "#121212"           # Near black background
secondaryBackgroundColor = "#1a1a1a"  # Sidebar/Cards
textColor = "#F5F5F5"                 # Light text for readability
font = "sans serif"                   # Clean modern font